// Catálogo generado desde la planilla (115 productos)
window.PRODUCTOS = [
  {
    "nombre": "Blusa Alaniz",
    "categoria": "Ropa adulto",
    "precio": 12990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla XS",
    "desc": "Color verde. Poco uso",
    "foto": "img/001.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Allsaints",
    "categoria": "Ropa adulto",
    "precio": 38990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color dorado. Poco uso",
    "foto": "img/002.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Desigual",
    "categoria": "Ropa adulto",
    "precio": 38990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negro. Poco uso",
    "foto": "img/003.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Guess",
    "categoria": "Ropa adulto",
    "precio": 38990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla L",
    "desc": "Color blanco y negro. Poco uso",
    "foto": "img/004.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Papaya",
    "categoria": "Ropa adulto",
    "precio": 20990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla M",
    "desc": "Color negro. Poco uso",
    "foto": "img/005.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Calvin Klein",
    "categoria": "Ropa adulto",
    "precio": 38990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negro. Poco uso",
    "foto": "img/006.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Desigual",
    "categoria": "Ropa adulto",
    "precio": 49990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color morado y verde. Poco uso",
    "foto": "img/007.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta Desigual",
    "categoria": "Ropa adulto",
    "precio": 49990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negro. Poco uso",
    "foto": "img/008.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta Rip Curl",
    "categoria": "Ropa adulto",
    "precio": 40990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color gris. Poco uso",
    "foto": "img/009.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido H&M",
    "categoria": "Ropa adulto",
    "precio": 38990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla XS",
    "desc": "Color negro. Poco uso",
    "foto": "img/010.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta Egoiste",
    "categoria": "Ropa adulto",
    "precio": 59990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla M",
    "desc": "Color negro. Poco uso",
    "foto": "img/011.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Umbrale",
    "categoria": "Ropa adulto",
    "precio": 22990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color café. Poco uso",
    "foto": "img/012.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Parka Abercrombie & Fitch",
    "categoria": "Ropa adulto",
    "precio": 13990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color rosado. Poco uso",
    "foto": "img/013.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta Bimba Y Lola",
    "categoria": "Ropa adulto",
    "precio": 65990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla XXS",
    "desc": "Color negra. Poco uso",
    "foto": "img/014.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Natalia Seguel",
    "categoria": "Ropa adulto",
    "precio": 39990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color blanco. Poco uso",
    "foto": "img/015.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Parka Robert Lewis",
    "categoria": "Ropa adulto",
    "precio": 39990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color blanco. Poco uso",
    "foto": "img/016.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Parka The North Face",
    "categoria": "Ropa adulto",
    "precio": 49990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color gris. Poco uso",
    "foto": "img/017.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta Foster Moon",
    "categoria": "Ropa niños",
    "precio": 20990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla 16",
    "desc": "Color animal print. Poco uso",
    "foto": "img/018.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta Leather Shop",
    "categoria": "Ropa adulto",
    "precio": 119990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negra. Poco uso",
    "foto": "img/019.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Parka Guess",
    "categoria": "Ropa adulto",
    "precio": 59990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negra. Poco uso",
    "foto": "img/020.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta Bershka",
    "categoria": "Ropa adulto",
    "precio": 129990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla M",
    "desc": "Color café. Poco uso",
    "foto": "img/021.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta Levis",
    "categoria": "Ropa adulto",
    "precio": 49990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla M",
    "desc": "Color negro. Poco uso",
    "foto": "img/022.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta Gian Mori",
    "categoria": "Ropa adulto",
    "precio": 99990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negro. Poco uso",
    "foto": "img/023.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta Prune",
    "categoria": "Ropa adulto",
    "precio": 99990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color café. Poco uso",
    "foto": "img/024.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Blazer Ming",
    "categoria": "Ropa adulto",
    "precio": 39990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negro. Poco uso",
    "foto": "img/025.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta Evoque",
    "categoria": "Ropa adulto",
    "precio": 49990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negro. Poco uso",
    "foto": "img/026.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Opposite",
    "categoria": "Ropa adulto",
    "precio": 5990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color beige. Poco uso",
    "foto": "img/027.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Abrigo Montgomery Cuero Argentino",
    "categoria": "Ropa adulto",
    "precio": 120990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color camel. Poco uso",
    "foto": "img/028.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Cinturon Michael Kors",
    "categoria": "Ropa adulto",
    "precio": 15990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla TU",
    "desc": "Color negro. Poco uso",
    "foto": "img/029.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Cinturon Negro",
    "categoria": "Ropa adulto",
    "precio": 12990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla TU",
    "desc": "Color negro. Poco uso",
    "foto": "img/030.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Zapatillas Adidas",
    "categoria": "Zapatillas",
    "precio": 39990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla 39,5",
    "desc": "Color gris. Poco uso",
    "foto": "img/031.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Zapatillas Bullpadel",
    "categoria": "Zapatillas",
    "precio": 39990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla 39",
    "desc": "Color blanco. Poco uso",
    "foto": "img/032.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chalas Grendha",
    "categoria": "Zapatillas",
    "precio": 25990,
    "precioAntes": 0,
    "estado": "Usado",
    "medidas": "Talla 39",
    "desc": "Color rosado. Usado",
    "foto": "img/033.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Zapatillas Lacoste",
    "categoria": "Zapatillas",
    "precio": 39990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla 39,5",
    "desc": "Color blanco. Poco uso",
    "foto": "img/034.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chalas Gold Forever",
    "categoria": "Zapatillas",
    "precio": 19990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla 38",
    "desc": "Color animal print. Poco uso",
    "foto": "img/035.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Botines Ugg",
    "categoria": "Zapatillas",
    "precio": 59990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla 39",
    "desc": "Color café. Poco uso",
    "foto": "img/036.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Zapatillas Converse",
    "categoria": "Zapatillas",
    "precio": 45990,
    "precioAntes": 0,
    "estado": "Nuevo",
    "medidas": "Talla 38,5",
    "desc": "Color negro. Nuevo",
    "foto": "img/037.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Zapatillas Tory Burch",
    "categoria": "Zapatillas",
    "precio": 39990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla 38",
    "desc": "Color blanco. Poco uso",
    "foto": "img/038.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Zapatillas Asics",
    "categoria": "Zapatillas",
    "precio": 34990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla 39,5",
    "desc": "Color negro. Poco uso",
    "foto": "img/039.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Zapatillas Veja",
    "categoria": "Zapatillas",
    "precio": 39990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla 38",
    "desc": "Color blanco. Poco uso",
    "foto": "img/040.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Zapatillas Nike",
    "categoria": "Zapatillas",
    "precio": 49990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla 40",
    "desc": "Color lila. Poco uso",
    "foto": "img/041.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Zapatillas Veja",
    "categoria": "Zapatillas",
    "precio": 39990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla 37",
    "desc": "Color dorado. Poco uso",
    "foto": "img/042.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Sosten Bikini Calzedonia",
    "categoria": "Traje de baño",
    "precio": 11990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla ST",
    "desc": "Color beige. Poco uso",
    "foto": "img/043.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Bikini Calzedonia",
    "categoria": "Traje de baño",
    "precio": 24990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla ST",
    "desc": "Color verde. Poco uso",
    "foto": "img/044.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Bikini Victoria Secret",
    "categoria": "Traje de baño",
    "precio": 39990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla 34D/S",
    "desc": "Color animal print negro. Poco uso",
    "foto": "img/045.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Bikini Hollister",
    "categoria": "Traje de baño",
    "precio": 19990,
    "precioAntes": 0,
    "estado": "Nuevo",
    "medidas": "Talla L/M",
    "desc": "Color azul. Nuevo",
    "foto": "img/046.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Traje De Baño Pat Pat",
    "categoria": "Traje de baño",
    "precio": 19990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla M",
    "desc": "Color blanco y verde. Como nuevo",
    "foto": "img/047.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Bikini Hurley",
    "categoria": "Traje de baño",
    "precio": 19990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla M",
    "desc": "Color blanco y verde. Como nuevo",
    "foto": "img/048.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Traje De Baño Old Navy",
    "categoria": "Traje de baño",
    "precio": 19990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla XS",
    "desc": "Color azul con verde. Como nuevo",
    "foto": "img/049.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Calzon Bikini Hollister",
    "categoria": "Traje de baño",
    "precio": 11990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla M",
    "desc": "Color rosado. Poco uso",
    "foto": "img/050.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Traje De Baño Lounge",
    "categoria": "Traje de baño",
    "precio": 14990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla XS",
    "desc": "Color naranja con brillos. Como nuevo",
    "foto": "img/051.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Sosten Bikini Flores",
    "categoria": "Traje de baño",
    "precio": 12990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla M",
    "desc": "Color rosado. Como nuevo",
    "foto": "img/052.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Sosten Bikini Flores",
    "categoria": "Traje de baño",
    "precio": 12990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color rosado. Como nuevo",
    "foto": "img/053.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Bikini Ondademar",
    "categoria": "Traje de baño",
    "precio": 24990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla S",
    "desc": "Color celeste. Poco uso",
    "foto": "img/054.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Bikini Calzedonia",
    "categoria": "Traje de baño",
    "precio": 24990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla ST",
    "desc": "Color celeste. Como nuevo",
    "foto": "img/055.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Sosten Bikini",
    "categoria": "Traje de baño",
    "precio": 9990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla ST",
    "desc": "Color rose gold. Como nuevo",
    "foto": "img/056.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Traje De Baño Patpat",
    "categoria": "Traje de baño",
    "precio": 19990,
    "precioAntes": 0,
    "estado": "Nuevo",
    "medidas": "Talla M",
    "desc": "Color negro. Nuevo",
    "foto": "img/057.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Bikini Hollister",
    "categoria": "Traje de baño",
    "precio": 19990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla L",
    "desc": "Color rosado. Como nuevo",
    "foto": "img/058.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Traje De Baño S/M",
    "categoria": "Traje de baño",
    "precio": 15990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla M",
    "desc": "Color negro. Poco uso",
    "foto": "img/059.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Falda",
    "categoria": "Ropa adulto",
    "precio": 9990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla M",
    "desc": "Color azul. Poco uso",
    "foto": "img/060.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Alaniz",
    "categoria": "Ropa adulto",
    "precio": 19990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla XS",
    "desc": "Color negro. Poco uso",
    "foto": "img/061.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido",
    "categoria": "Ropa niños",
    "precio": 11990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla 11",
    "desc": "Color azul. Como nuevo",
    "foto": "img/062.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Falda",
    "categoria": "Ropa adulto",
    "precio": 14990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla M",
    "desc": "Color animal print. Como nuevo",
    "foto": "img/063.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Abercrombie & Fitch",
    "categoria": "Ropa adulto",
    "precio": 19990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla XS",
    "desc": "Color blanco. Como nuevo",
    "foto": "img/064.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera",
    "categoria": "Ropa adulto",
    "precio": 4990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla S",
    "desc": "Color azul. Poco uso",
    "foto": "img/065.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Wild Llama",
    "categoria": "Ropa adulto",
    "precio": 14990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla XS",
    "desc": "Color rosado. Como nuevo",
    "foto": "img/066.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Roxy",
    "categoria": "Ropa adulto",
    "precio": 9990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla M",
    "desc": "Color rojo. Poco uso",
    "foto": "img/067.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Opposite",
    "categoria": "Ropa adulto",
    "precio": 11990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negro. Como nuevo",
    "foto": "img/068.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido PatPat",
    "categoria": "Ropa adulto",
    "precio": 12990,
    "precioAntes": 0,
    "estado": "Nuevo",
    "medidas": "Talla M",
    "desc": "Color negro. Nuevo",
    "foto": "img/069.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido PatPat",
    "categoria": "Ropa adulto",
    "precio": 12990,
    "precioAntes": 0,
    "estado": "Nuevo",
    "medidas": "Talla S",
    "desc": "Color negro. Nuevo",
    "foto": "img/070.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Enterito Natalia Seguel",
    "categoria": "Ropa adulto",
    "precio": 18990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color azul. Como nuevo",
    "foto": "img/071.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera",
    "categoria": "Ropa adulto",
    "precio": 7990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color rosado. Como nuevo",
    "foto": "img/072.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido BCBGMAXAZRIA",
    "categoria": "Ropa adulto",
    "precio": 18990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negro. Como nuevo",
    "foto": "img/073.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido ENFOCUS",
    "categoria": "Ropa adulto",
    "precio": 18990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla S",
    "desc": "Color beige. Poco uso",
    "foto": "img/074.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Blusa Desigual",
    "categoria": "Ropa adulto",
    "precio": 16990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla XS",
    "desc": "Color azul. Como nuevo",
    "foto": "img/075.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera",
    "categoria": "Ropa adulto",
    "precio": 6990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla S",
    "desc": "Color animal print. Poco uso",
    "foto": "img/076.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Armani Exchange",
    "categoria": "Ropa adulto",
    "precio": 24990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla S",
    "desc": "Color negro. Poco uso",
    "foto": "img/077.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Falda Sybilla",
    "categoria": "Ropa adulto",
    "precio": 13990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color verde. Como nuevo",
    "foto": "img/078.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Falda Abercrombie Kids",
    "categoria": "Ropa niños",
    "precio": 11990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla 16",
    "desc": "Color blanco. Como nuevo",
    "foto": "img/079.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido",
    "categoria": "Ropa adulto",
    "precio": 17990,
    "precioAntes": 0,
    "estado": "Nuevo",
    "medidas": "Talla S",
    "desc": "Color blanco. Nuevo",
    "foto": "img/080.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Miss Veil",
    "categoria": "Ropa adulto",
    "precio": 29990,
    "precioAntes": 0,
    "estado": "Nuevo",
    "medidas": "Talla S",
    "desc": "Color blanco. Nuevo",
    "foto": "img/081.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido",
    "categoria": "Ropa adulto",
    "precio": 25990,
    "precioAntes": 0,
    "estado": "Nuevo",
    "medidas": "Talla S",
    "desc": "Color blanco. Nuevo",
    "foto": "img/082.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Mac Douggal",
    "categoria": "Ropa adulto",
    "precio": 44990,
    "precioAntes": 0,
    "estado": "Nuevo",
    "medidas": "Talla S",
    "desc": "Color gris. Nuevo",
    "foto": "img/083.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Falda Scalpers",
    "categoria": "Ropa adulto",
    "precio": 15990,
    "precioAntes": 0,
    "estado": "Usado",
    "medidas": "Talla L",
    "desc": "Color blanco. Usado",
    "foto": "img/084.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Pantalones Costes",
    "categoria": "Ropa adulto",
    "precio": 13990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color animal print. Como nuevo",
    "foto": "img/085.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Blazer Express",
    "categoria": "Ropa adulto",
    "precio": 12990,
    "precioAntes": 0,
    "estado": "Usado",
    "medidas": "Talla XS",
    "desc": "Color negro y blanco. Usado",
    "foto": "img/086.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Enterito Emery Rose",
    "categoria": "Ropa adulto",
    "precio": 14990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color rosado. Como nuevo",
    "foto": "img/087.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta Levis",
    "categoria": "Ropa adulto",
    "precio": 19990,
    "precioAntes": 0,
    "estado": "Usado",
    "medidas": "Talla M",
    "desc": "Color jean. Usado",
    "foto": "img/088.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Vestido Kaya Unite",
    "categoria": "Ropa adulto",
    "precio": 13990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla S",
    "desc": "Color azul. Poco uso",
    "foto": "img/089.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Blazer Alaniz",
    "categoria": "Ropa adulto",
    "precio": 12990,
    "precioAntes": 0,
    "estado": "Usado",
    "medidas": "Talla S",
    "desc": "Color gris. Usado",
    "foto": "img/090.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Blazer Marittimo",
    "categoria": "Ropa adulto",
    "precio": 12990,
    "precioAntes": 0,
    "estado": "Usado",
    "medidas": "Talla S",
    "desc": "Color verde. Usado",
    "foto": "img/091.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Chaqueta",
    "categoria": "Ropa adulto",
    "precio": 14990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color jean. Como nuevo",
    "foto": "img/092.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Enterito Abercrombie Kids",
    "categoria": "Ropa niños",
    "precio": 11990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla 16",
    "desc": "Color blanco. Como nuevo",
    "foto": "img/093.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera Express",
    "categoria": "Ropa adulto",
    "precio": 8990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color gris. Como nuevo",
    "foto": "img/094.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera Be Huna",
    "categoria": "Ropa adulto",
    "precio": 13990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color rojo. Como nuevo",
    "foto": "img/095.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera",
    "categoria": "Ropa adulto",
    "precio": 11990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color blanco. Como nuevo",
    "foto": "img/096.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera Massimo",
    "categoria": "Ropa adulto",
    "precio": 6990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negro. Como nuevo",
    "foto": "img/097.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera Zara",
    "categoria": "Ropa adulto",
    "precio": 13990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla M",
    "desc": "Color blanco. Como nuevo",
    "foto": "img/098.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Body",
    "categoria": "Ropa adulto",
    "precio": 11990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color animal print. Como nuevo",
    "foto": "img/099.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera American Eagle",
    "categoria": "Ropa adulto",
    "precio": 7990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla XS",
    "desc": "Color azul. Poco uso",
    "foto": "img/100.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Body Americanino",
    "categoria": "Ropa adulto",
    "precio": 5990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla S",
    "desc": "Color rojo. Poco uso",
    "foto": "img/101.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera Tezenis",
    "categoria": "Ropa adulto",
    "precio": 5990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla S",
    "desc": "Color rosado. Poco uso",
    "foto": "img/102.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Blusa Da Moda",
    "categoria": "Ropa adulto",
    "precio": 7990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color animal print. Como nuevo",
    "foto": "img/103.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera Pink",
    "categoria": "Ropa adulto",
    "precio": 5990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla XS",
    "desc": "Color animal print. Poco uso",
    "foto": "img/104.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Body Total y Sexy",
    "categoria": "Ropa adulto",
    "precio": 7990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negro. Como nuevo",
    "foto": "img/105.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Body Honey Punch",
    "categoria": "Ropa adulto",
    "precio": 6990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla M",
    "desc": "Color negro. Poco uso",
    "foto": "img/106.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera Taco",
    "categoria": "Ropa adulto",
    "precio": 5990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color azul. Como nuevo",
    "foto": "img/107.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Body Express",
    "categoria": "Ropa adulto",
    "precio": 7990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla XS",
    "desc": "Color azul. Como nuevo",
    "foto": "img/108.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Body Karl Lagerfeld",
    "categoria": "Ropa adulto",
    "precio": 7990,
    "precioAntes": 0,
    "estado": "Nuevo",
    "medidas": "Talla S",
    "desc": "Color blanco. Nuevo",
    "foto": "img/109.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera Taco",
    "categoria": "Ropa adulto",
    "precio": 5990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla M",
    "desc": "Color amarillo. Como nuevo",
    "foto": "img/110.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Polera Dreamr",
    "categoria": "Ropa adulto",
    "precio": 6990,
    "precioAntes": 0,
    "estado": "Poco uso",
    "medidas": "Talla M",
    "desc": "Color negro. Poco uso",
    "foto": "img/111.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Falda Abercrombie Kids",
    "categoria": "Ropa niños",
    "precio": 8990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla 16",
    "desc": "Color negro. Como nuevo",
    "foto": "img/112.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Body Pull & Bear",
    "categoria": "Ropa adulto",
    "precio": 9990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla M",
    "desc": "Color gris. Como nuevo",
    "foto": "img/113.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Body Zara",
    "categoria": "Ropa adulto",
    "precio": 8990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color verde. Como nuevo",
    "foto": "img/114.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  },
  {
    "nombre": "Body Zara",
    "categoria": "Ropa adulto",
    "precio": 8990,
    "precioAntes": 0,
    "estado": "Como nuevo",
    "medidas": "Talla S",
    "desc": "Color negro. Como nuevo",
    "foto": "img/115.jpg",
    "estadoVenta": "disponible",
    "linkPago": ""
  }
];
